### ISSUE TITLE
'data/glove.6B.50d.txt' not found

### ISSUE THREAD

**Issue by wnma3mz** [cryer/Emojify#1]
https://github.com/cryer/Emojify/blob/63d1cc9a41b9c00fd2a5d0a6e994698f83d0bfad/emojify.py#L51

在`data`文件夹中缺失了这个文件

**Comment by cryer** [comment]
对，这个文件有一点点大，没有上传到github，我上传到谷歌云盘上了，readme文档里给了地址了

**Comment by wnma3mz** [comment]
Thanks, 已找到
